// EnvelopeSealKATVectors.swift — GENERATED by tools/gen_envelope_seal_kat.py.
// DO NOT EDIT. Independent pure-Python X25519 / HKDF-SHA256 / ChaCha20-Poly1305,
// self-checked against RFC 7748 §5.2 + §6.1, RFC 5869 A.1 + A.3, RFC 8439 §2.8.2.

import Foundation

enum EnvelopeSealKATVectors {
    struct Vector {
        let recipientPrivate: String
        let recipientPublic: String
        let ephemeralPrivate: String
        let ephemeralPublic: String
        let inner: String
        let sealed: String
    }

    static let all: [Vector] = [
        Vector(
            recipientPrivate: "2024e93d2d4338624415620a7cecf838d0d83df1af94064b678dacdb8cf94788",
            recipientPublic: "53b5e617003683181d2c8fb81bd0209618824de619879fee9e7ffe51f3793732",
            ephemeralPrivate: "33ec8bc82adabbd0c1bdb34304d52ffb9abf2e9d31682629183e786a025cd3ce",
            ephemeralPublic: "69a7c18bf1d569897fd1731e5021bf8d771ac6a500d725cc110f79a3371e0c6c",
            inner: "",
            sealed: "0169a7c18bf1d569897fd1731e5021bf8d771ac6a500d725cc110f79a3371e0c6c9eb2f71675f7e400e83dfac45e49dd54"
        ),
        Vector(
            recipientPrivate: "51f9e277ed2f538cb794acc211ffa284940637b055c79bc702b0d380ea610b32",
            recipientPublic: "ffe338fc4e471de5f991dfcdc2066758da8e09469320b26c66a5f1109182352e",
            ephemeralPrivate: "a26a432e403345c8c02d4d13bea72a732ea331f8a6277b731157fa1e2170b878",
            ephemeralPublic: "1a09e3813d23447d59c7ffa853bf8bc031a1e5617213a9288ca343f1d930271f",
            inner: "c1",
            sealed: "011a09e3813d23447d59c7ffa853bf8bc031a1e5617213a9288ca343f1d930271f0f654e8ce4d4f99e846ac0871806d8819c"
        ),
        Vector(
            recipientPrivate: "d54d97fb143844b49c321e0ace4e191c1c503b251e366f0e91c6cc7ef8c976ed",
            recipientPublic: "7620f5e8d13ab165edc45d2240fb99b8bedc452de7aa99963e319f6ee639925c",
            ephemeralPrivate: "2e8722f4631baa6dbdceb1b7ca96ec2adc6e6876d09002e4a4b7b4b4dfc4dbec",
            ephemeralPublic: "f4616ab5277ad1fe147b23259d010b6432b8045eb5f04ea4de9dc93ea7bad239",
            inner: "863ee5ddc26066b065e853e3f47298727e04bd794ebe4f31acd51866c5e181355c",
            sealed: "01f4616ab5277ad1fe147b23259d010b6432b8045eb5f04ea4de9dc93ea7bad23950d646f2a9e434cb36a134d86699afc279a4f3eaaeaeabc02776e9b2da537158438060c147e050a1293d05a1e5f96684c9"
        ),
        Vector(
            recipientPrivate: "8f8d749c1056ae2c44eccd80c36da2c59c3aa704a0a36bb39b5807432ab155ef",
            recipientPublic: "82e8983ed04bec57362f9d4819017be7fdfba32e4506629f6736589304589d28",
            ephemeralPrivate: "96e930fd24fe65c09db327b1d53811d90386f20f6329f83efd4ffd41ae77e385",
            ephemeralPublic: "3eea3494f2a628d892a3bcfe115d6c7e64656e5af7587664a7426323c4fb4d7d",
            inner: "ac0f5199dc2f9155f2002b47794f8b5da34cfb6441c1a5be6d50bc8840689b4dadf45a5c7f704f0cca0d54715030f1a3e34d7655d7edb9b195920ad4236d3c1d",
            sealed: "013eea3494f2a628d892a3bcfe115d6c7e64656e5af7587664a7426323c4fb4d7d12c3e2d385bc76309ec7dad7b6ba171d20ce585ac74054468be04ebc9f60d4b6c3e420207f282bbcf62795162efbd17f18c61f1e793eaa69712793b27b6b71be843dc0063c693de4be99fd9cd9e7e2e5"
        ),
        Vector(
            recipientPrivate: "d243cff61269045f0ad00a739091a02e5e8f2cb4afb5492475d9f516b427fe30",
            recipientPublic: "7e62ce1e6739b6f75924356d25ec91304ca30b70deb2d61651dd9271ca3e0c32",
            ephemeralPrivate: "31370bb267526a44df807041d55a571611432e0265787846d59e4664176e0135",
            ephemeralPublic: "b748186a5360b991e3695b44f3bccd23c1fd7d8da8f75091808f0b046972803b",
            inner: "a7f24f213ba6f0551edcdd760b1d1a368e4975b14983d74c6522986485bec49e8c3d48f42fc6d6fb34acfabc8aefd6cb8a986d0161f10e26bf4c7e5ebbf7f3239ad4900296fbe0d969c3a83285d25af89a05325dedaaa26e1c212b46b9989524ccea0f4f4eec45e2d680d63a9d60f97ce185771bf14c8125efab8de737ccf4bf64b103928e6e430c6029531d56144ecf091c0b5a31a87b1e04ae7dada2e59ff7e83c0f04b743fd616938b9b133df50293359acee73c7be2b0a522b7c97a98f5b8c69495462afd5d14e30ad7326d0c47eb72789291ecf3029bc734aa4e2b2a949ed59b4d30b97a2a61115772ea25de48d596c4a3464c57c90492aecbc1b2531a28d571a02e84925ca157367b1d8752693a5b548720dde7806f8572a210a10958552fd3107636fef7de0540f9f",
            sealed: "01b748186a5360b991e3695b44f3bccd23c1fd7d8da8f75091808f0b046972803b8686c4855646a7970ebdc6665a4e99013bd21aeaaf748dd1b85c7713c2a6049a2d89b33d09e95a39e36eeef00e427dd03577a2b86f94b242ac252591f6cfeaa79dd4bfda109c36b92d8f4a5f076149db09d48d98da96901a259ab47e3e867fa10da09a8c89e32d794501e83b066ea3de5898065f58819a0d08eef6037f93430c0e9bf1bae8cd64c25d4c4fdef59ebedc21130a6eb8ab5c6f433d00b99a8d68054ca301974d3369454590e70ce7abadb2052bddddab20f7cc3e2f8fdc51f82ec39d7ea38acbe8705074f3f2628f8c57f125b10758cd49713c8aa190f3db8ed15257a7da166c56228e009cfe03080498dbfcb29c018840a04614d37baaefb3e59a1ad61b6cd04998a6e372275ae1e103cdb18260642ef70b8f3691181ab34005bf72573c4dfc2b21164a178a6427f3971730b3c54de6c0681097227372"
        ),
    ]
}
